server:
  port: 8091
druid:
  allow:
    ip: 127.0.0.1
  login:
    user_name: root
    password: root
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:jdbc: mysql://120.78.185.109:3306/xdclass_coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500